#!/bin/bash
file="file_path"

if [ -e "$file" ]; then
  echo "file_path passwords are enabled."
  
  if [ -w "$file" ]; then
    echo "You have permissions to edit file_path."
  else
    echo "You do NOT have permissions to edit file_path."
  fi
else
  echo "file_path does not exist."
fi
